export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const SUCCESSFUL_REGISTER = 'SUCCESSFUL_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';
export const CLEAN_ALERT = 'CLEAN_ALERT';

