export const AUTHENTICATED_USER = 'AUTHENTICATED_USER';
export const SUCCESSFUL_REGISTER = 'SUCCESSFUL_REGISTER';
export const ERROR_REGISTER = 'ERROR_REGISTER';

export const SUCESSFUL_LOGIN = 'SUCESSFUL_LOGIN';
export const ERROR_LOGIN = 'ERROR_LOGIN';
export const LOGOUT = 'LOGOUT';

export const CLEAN_ALERT = 'CLEAN_ALERT';
export const SHOW_ALERT = 'SHOW_ALERT';

export const UPLOAD_FILE_LOADING = 'UPLOAD_FILE_LOADING';
export const UPLOAD_FILE_SUCCESS = 'UPLOAD_FILE_SUCCESS';
export const UPLOAD_FILE_ERROR = 'UPLOAD_FILE_ERROR';

export const CREATE_LINK_SUCCESS = 'CREATE_LINK_SUCCESS';
export const CREATE_LINK_ERROR = 'CREATE_LINK_ERROR';

export const CLEAN_STATE = 'CLEAN_STATE';

export const ADD_PASSWORD = 'ADD_PASSWORD';
export const ADD_DOWNLOAD_LIMIT = 'ADD_DOWNLOAD_LIMIT';
